### PR TITLE
update mypy from 0.730 to 0.740

### PR DESCRIPTION
**Pull request by ammarnajjar**
Issue #917

# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

### CODE REVIEW

**Comment by sobolevn** [comment]
Hi, @ammarnajjar! Thanks for your help! 

Can you please also fix this issue:

```
mypy wemake_python_styleguide
wemake_python_styleguide/logic/safe_eval.py:84: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior
Found 1 error in 1 file (checked 102 source files)
```

**Comment by ammarnajjar** [comment]
glad to.
The thing is that I don't get this error locally.. so it's kinda try&error for me.

**Comment by sobolevn** [comment]
@ammarnajjar strange. Can you please show you `mypy --version` from local machine?

**Comment by ammarnajjar** [comment]
that's  embarrassing 😅 , I forgot to shell into poetry.. (first time using poetry to say the truth). 
after shelling, I got the mentioned error. Thanks for the hint.

**Comment by sobolevn** [comment]
Thanks a lot!

**Pull request merged**
