### PR TITLE
flakehell -> flakeheaven

### LINKED ISSUE #2519: Docs: change the recommendation to use flakehell (not maintainable) -> flakeheaven
### What's wrong

WPS recommend using `flakehell` for legacy codebase, but [flakehell](https://github.com/flakehell/flakehell) not supported. [Discussion](https://github.com/flakehell/flakehell/issues/30) about archiving the repository.

May be change recomendation to [flakeheaven](https://github.com/flakeheaven/flakeheaven)?

### How it should be

N/A

### Flake8 version and plugins

N/A

### pip information

N/A

### OS information

N/A

### PR DESCRIPTION
**Pull request by blablatdinov**
# I have made things!

Replaced `flakehell` mentions to `flakeheaven`

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues

- Closes #2519 

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

### CODE REVIEW

**Comment by blablatdinov** [comment]
@sobolevn review my changes, please

**Review by sobolevn — APPROVED** [review]
I am not sure that all examples are still valid, but it is fine to update them later.

Thanks!

**Comment by Xezed** [comment]
Ahhh, I found a guy who broke our deployment :D 
We used flakehell as a base for our config :) @blablatdinov

**Comment by sobolevn** [comment]
@Xezed can you please share more details about your issue?

**Comment by sobolevn** [comment]
Oh, I now see. We need to revert `styles/flakehell.toml`.
We can just add `styles/flakeheaven.toml`. But, the old file must still be present.

I will fix it in a moment. Sorry for this!

**Comment by Xezed** [comment]
I just replaced it with: https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/0.16.1/styles/flakehell.toml

**Pull request merged**
