### PR TITLE
Add LGTM code quality shield

### PR DESCRIPTION
**Pull request by AlexTereshenkov**
I am adding a shield to demonstrate the exemplary quality of Python code compared to other Python projects.

I have also added this style guide project to LGTM.com so each commit will be analyzed to see if any alert is introduced. Project overview page is accessible [here](https://lgtm.com/projects/g/wemake-services/wemake-python-styleguide/overview/).

Nearly all queries from the [Python queries suite](https://help.semmle.com/wiki/display/PYTHON/Python+queries) will be run on each commit. It is also possible to add existing custom queries, for instance, this one: [Accepting unknown SSH host keys when using Paramiko](https://github.com/Semmle/ql/blob/2ba122373acd660ea0c2fb148d6ee2e1e8732dca/python/ql/src/Security/CWE-295/MissingHostKeyValidation.ql) or even write custom queries using QL, for instance, [Find all Python identifiers with a non-ASCII character](https://lgtm.com/query/3123831890641430639/). If you have an idea of what you would like to test in Python code, please do let me know as I could add it to your project to be run on each commit.

You can also use LGTM as a continuous integration tool to automatically review code in pull requests before it reaches your main branch. Read more [here](https://lgtm.com/projects/g/wemake-services/wemake-python-styleguide/ci/). The alerts won't impede you from merging a PR; you can choose what is important for you. If you feel you are not ready for this, no worries, I'll check periodically the LGTM project overview page to see for any new alerts being introduced and will post an issue / submit a PR.

### CODE REVIEW

**Comment by sobolevn** [comment]
Awesome!

The only thing that bothers me is that labels do not fit into a single screen:
Снимок экрана 2019-06-07 в 16 55 48

Maybe we should split them: one line for information, one line for code quality.
What do you think?

**Comment by AlexTereshenkov** [comment]
Absolutely! Which of the shields relate to the code quality / information?

**Comment by sobolevn** [comment]
Info: wemake.services, python versions, style
Build: travis, coverage, docs, dependencies, lgtm

Btw, is there a shorter version of your badge? It would be awesome to have one.

**Comment by AlexTereshenkov** [comment]
> Btw, is there a shorter version of your badge? It would be awesome to have one.

Unfortunately we currently don't have a smaller version. I've logged a request to issue one.

**Pull request merged**
