### PR TITLE
Update reviewdog to 0.11.0 and add action-depup

### LINKED ISSUE #1698: Update reviewdog to 0.11
We use `reviewdog@0.9`, but `0.11` is released.
https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md#v0110---2020-10-25

Related: https://github.com/wemake-services/wemake-python-styleguide/blob/master/Dockerfile#L24

### PR DESCRIPTION
**Pull request by mgrachev**
# I have made things!

I have updated `reviewdog` to `v0.11.0` and also added [action-depup](https://github.com/haya14busa/action-depup) to automatically update reviewdog in the future.

Close #1698 

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thanks a lot! I didn't know about `depup`, this seems cool!

**Comment by sobolevn** [comment]
Related https://github.com/Zac-HD/hypothesmith/issues/12

**Comment by haya14busa** [comment]
@mgrachev depup yml should be under workflows directory?

**Comment by sobolevn** [comment]
@mgrachev yes, looks like @haya14busa is right!

**Comment by mgrachev** [comment]
Yes, you are right. It is my mistake 😔

**Comment by mgrachev** [comment]
Fixed https://github.com/wemake-services/wemake-python-styleguide/pull/1722 😅

**Pull request merged**
