### PR TITLE
Test pr

### PR DESCRIPTION
**Pull request by lk-geimfari**
This is a PR to testing integration with AppVeyor.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
Hooray!

**Comment by sobolevn** [comment]
Awesome, let's wait for the build to succeed.

**Comment by lk-geimfari** [comment]
@sobolevn It works really slowly, but [this](https://ci.appveyor.com/project/wemake-services/wemake-python-styleguide/build/1.0.2/job/ryqw1954wxh4764g) make me believe that all test on Windows will pass.

**Comment by lk-geimfari** [comment]
@sobolevn So, this works fine. All tests are passed. I guess we can close this PR and delete this branch.

**Comment by lk-geimfari** [comment]
@sobolevn Also, to refresh badge in readme, please trigger new build in AppVeyyor account.

**Comment by sobolevn** [comment]
@lk-geimfari thank you very much!

**Pull request closed without merging**
