### PR TITLE
bugfix #819 updated mypy to latest package via poetry

### LINKED ISSUE #819: Update mypy to the latest version
Some old type errors are gone: https://github.com/wemake-services/wemake-python-styleguide/pull/818

### PR DESCRIPTION
**Pull request by viveksoundrapandi**
# I have made things!

## Checklist

- [ ] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #819
Closes #818

### CODE REVIEW

**Comment by sobolevn** [comment]
@viveksoundrapandi please, fix the CI and I will merge it.

**Comment by sobolevn** [comment]
@viveksoundrapandi ?

**Comment by viveksoundrapandi** [comment]
Great, will do it

**Comment by viveksoundrapandi** [comment]
@sobolevn I have addressed the fix but now the build is broken due to connection timeout while installing mypy. Can you retrigger the JOB

**Comment by sobolevn** [comment]
Thanks a lot!

**Pull request merged**
