### PR TITLE
use abc stdlib module to mark abstract classes

### LINKED ISSUE #1121: Make abstract classes abstract
There are several classes that are not marked as `abstract`. But, they should be!

Like:
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/base.py
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/base.py

We need to import `abc` and use `metaclass=ABCMeta` for all of them.

### PR DESCRIPTION
**Pull request by skarzi**
# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [x] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #1121 

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

### CODE REVIEW

**Comment by skarzi** [comment]
`abc.ABC` is just small helper - it is `object`'s subclass that use `abc.ABCMeta` metaclass, so it just makes most common abstract classes definitions more concise.
Generally any class that subclass some ABC class and do NOT override **all** abstract methods is also ABC class, that's the reason I haven't add `metaclass=abc.ABCMeta` to [`BaseFilenameVisitor`](https://github.com/wemake-services/wemake-python-styleguide/blob/53b98be42f8e8be9993c62b3f856478f9dc5ea3c/wemake_python_styleguide/visitors/base.py#L182) however I have used `@abc.abstractmethod` decorator on `visit_filename()`.

We can add `metaclass=abc.ABCMeta` to other classes, however they aren't real ABC classes, because they already implement `run()` method (which is the only abstract method they need to implement), so it will be just an information to developers

**Comment by skarzi** [comment]
Similar story with all violations' base classes, but there even `BaseViolation` is not a real ABC class, because it doesn't declara any abstract method, however still we can make its class attributes abstract by using 2nd or 3rd solution that I have mentioned in issue #1121 [comment](https://github.com/wemake-services/wemake-python-styleguide/issues/1121#issuecomment-578401954)

**Comment by sobolevn** [comment]
> so it will be just an information to developers
Yes, please! That was the main idea behind this change.
Sometimes developers what to see what classes are *base* ones (that how this task was originally born). And this (I hope) is going to help them.

**Comment by sobolevn** [comment]
Thanks a lot! 😄

**Pull request merged**
