### PR TITLE
Issue#864

### PR DESCRIPTION
**Pull request by ManishAradwad**
# I have made things!

## Checklist

- [ ] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

#864 

@sobolevn  Can you plz help me with the logic, I don't know how to do it...
Thanks for help!

### CODE REVIEW

**Comment by sobolevn** [comment]
Oh, that's quite a complex one. I am not sure how to approach this one either.

I would recommend to start with simple programs that has this problem.
1. Write `ex.py` with code that violates this rule
2. Run `astboom` on this file to visualise what you are getting
3. Go from there to implement some basic logic

**Comment by sobolevn** [comment]
You can also take some task that is easier if you wish https://github.com/wemake-services/wemake-python-styleguide/issues/1077

**Comment by ManishAradwad** [comment]
Sure! Thank You.

**Comment by sobolevn** [comment]
Closing for now, feel free to reopen.

**Pull request closed without merging**
