### PR TITLE
Any PR for test

### PR DESCRIPTION
**Pull request by lk-geimfari**

### CODE REVIEW

**Comment by sobolevn** [comment]
Integration is not working. Why on earth it is so complicated?

**Comment by lk-geimfari** [comment]
@sobolevn Seems like it does not work. Can you please delete both project from your AppVeyor account add add them again?

**Comment by sobolevn** [comment]
It worked after complete delete/add new cycle. https://ci.appveyor.com/project/wemake-services/wemake-python-styleguide

**Comment by sobolevn** [comment]
@lk-geimfari can you please try a new PR, please?

**Comment by lk-geimfari** [comment]
@sobolevn Sure!

**Pull request closed without merging**
