### PR TITLE
added __subclasses__ and __mro__ to exclusions of DirectMagicAttributeAccessViolation

### LINKED ISSUE #1314: False positive DirectMagicAttributeAccessViolation with __subclasses__
# Bug report

## What's wrong
```python
class MyClass(object):
    """My class."""

subs = MyClass.__subclasses__()
```

This piece of code raises
`WPS609 Found direct magic attribute usage: __subclasses__`

## How is that should be
`__subclasess__` method should be excluded from the check because it's a class method and can be used outside of class.

Maybe there are other methods that should be excluded?

### PR DESCRIPTION
**Pull request by mattany**
## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #1314

### CODE REVIEW

**Comment by mattany** [comment]
I looked at some of the test cases in the file ```test_magic_attributes.py``` and many of them won't compile for sure but do pass the tests without errors. This is because the "method" and "attribute" tests are done in conjunction. Is this on purpose? 
For example in the test ```test_magic_attribute_is_restricted``` the case ```magic_method_called``` will replace {0} with __class__ :
```'some.__class__()'``` 
which throws no style exception.
I'm guessing this is okay because we trust the person to try and run the code before running the linter

**Comment by mattany** [comment]
Also I think that the names of the last two functions in the test are quite misleading: 
```test_regular_attributes``` and ```test_whitelist_magic_attributes_are_allowed``` run on the same ```attribute``` parameter list which includes both ```'regular'``` and the special cases ```__name__``` etc. The difference is only in the code fragments that the functions run on:
-```test_regular_attributes```  runs on the 'wrong' cases.
-```test_whitelist_magic_attributes_are_allowed``` runs on the 'correct' cases.
Both tests pass iff no errors were thrown.

**Comment by mattany** [comment]
> It means that we need to raise errors on both calls and attributes.
> You can rename tests the way you wish! Thanks for the suggestion.

So how should I proceed from here? My understanding is that the exception needs to be thrown under different circumstances. Should I try and fix the place where the exception is called and then update it and update the tests and issue a new pull request?

**Comment by sobolevn** [comment]
@mattany sorry, I am a bit lost in the discussion 🙂 

Why cannot we just add the needed values here: https://github.com/wemake-services/wemake-python-styleguide/blob/58b96219a39390c35353aa9a29d483d5ed3f1cf7/tests/test_visitors/test_ast/test_attributes/test_magic_attributes.py#L181 ?

**Comment by mattany** [comment]
It's no problem to add them there and in the other test, but since we established that the exception doesn't capture some cases, I assumed we would want to fix that first. I guess your right though - it's better to first close this issue first before addressing the next.

**Pull request closed without merging**
