### PR TITLE
Fixed links in web version of CONTRIBUTING doc

### PR DESCRIPTION
**Pull request by Chinmaygoyal**
# I have made things!

## Checklist

- [ ] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have updated the documentation for the changes I have made

### CODE REVIEW

**Comment by Chinmaygoyal** [comment]
Can you please help me understand where I went wrong because I only made changes to CONTRIBUTING.md file?

**Comment by Chinmaygoyal** [comment]
Can you help me understand where I went wrong as I only made changes in CONTRIBUTING.md?

**Comment by sobolevn** [comment]
@Chinmaygoyal that's not related to these changes. 

Thanks a lot for your work! I will fix the CI and merge this PR soon.
🎉

**Comment by sobolevn** [comment]
Thanks again, I have fixed all problems with the dependencies. Merging.

**Pull request merged**
