### PR TITLE
Forbid negated conditions

### PR DESCRIPTION
**Pull request by mikhail-akimov**
Violation added, visitor created and I'm stuck:
How could i test my visitor's logic during development? I created a test file, with the correct and wrong cases into it, and try to check with the `flake8 test.py`, but my visitor does not apply to verification.

What is the best way to test logic during development?

### CODE REVIEW

**Comment by sobolevn** [comment]
Well, you should add your `visitor` to a preset. Then it will be enabled an you can use it with `flake8 test.py`

**Comment by mikhail-akimov** [comment]
Thank you!

**Comment by mikhail-akimov** [comment]
You meant the presets\general.py ?

**Comment by sobolevn** [comment]
Yes, `presets/general.py`

**Comment by mikhail-akimov** [comment]
I add new `NegatedConditionsViolation` to Summary and Design in best-practices.py and got my class from `conditions.py` started worked! But i can not understand how it works. Could you give me the way to discover it?

**Comment by mikhail-akimov** [comment]
Could i try to resolve conflicts? I`ll move this rule manually to the end.

**Comment by sobolevn** [comment]
Hey @mikhail-akimov, I have resolved conflicts for you. 👍

**Comment by mikhail-akimov** [comment]
I think i did something wrong... Review please conditions.py. Is it ok or i have to improve anything?

**Comment by sobolevn** [comment]
Awesome work, @mikhail-akimov! I really appreciate your help.
Feel free to take any other tasks when you will be ready.

**Pull request merged**
