### PR TITLE
Issue 2193

### LINKED ISSUE #2193: `recommonmark` is deprecated
https://github.com/readthedocs/recommonmark#recommonmark

We should switch to `myst`: https://github.com/executablebooks/MyST-Parser

### PR DESCRIPTION
**Pull request by ShehanAT**
I replaced the depreciated package: `recommonmark` with it's replacement package: `myst-parser` in the ```docs/requirements.txt``` file. I also added an entry in the `CHANGELOG.md` file to reflect this change.

## Checklist
- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [x] I have created at least one test case for the changes I have made
- [x] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues
- Closes #2193 

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

### CODE REVIEW

**Comment by sobolevn** [comment]
Can you please also take a look: do we need / can we drop `m2r2`? https://github.com/wemake-services/wemake-python-styleguide/blob/master/docs/conf.py#L60-L61

**Comment by ShehanAT** [comment]
@sobolevn I have ran ```make test``` after commenting out ```m2r2==0.3.1``` in the ```docs/requirements.txt``` file and all tests pass successfully. In order to remove ```m2r2```, should I remove it's references from the ```docs/conf.py``` and ```pyproject.toml``` files as well?

**Comment by sobolevn** [comment]
@ShehanAT yes, please! 🚀

**Comment by ShehanAT** [comment]
@sobolevn Ok done!

**Comment by sobolevn** [comment]
I've tried to locally build our docs with `myst` installed and it failed 😞 

There are so many errors, warnings, and issues, that I think it is not worth it.
I am really sorry, but I am going to close this PR. I though it is just a drop-in replacement.

Please, feel free to take any other issue. 🙏

**Comment by sobolevn** [comment]
@ShehanAT for example, https://github.com/wemake-services/wemake-python-styleguide/issues/2195 🙂

**Pull request closed without merging**
