### PR TITLE
Consistency spelling and grammar

### PR DESCRIPTION
**Pull request by waterseeker**
# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thanks!

**Comment by waterseeker** [comment]
Sorry, I'm still having the issue with the prior changes to base.py showing up as new in my PRs. I don't understand why they are still showing up, they aren't showing on my local with I run git status, only when I compare my fork to the main repo. But if I do a git pull, the changes are still there.

**Comment by waterseeker** [comment]
How did you resolve that before?

**Comment by sobolevn** [comment]
It will go away once merged! Thanks!

**Comment by waterseeker** [comment]
Ok, thanks!

**Pull request merged**
