### PR TITLE
closes issue-858

### PR DESCRIPTION
**Pull request by raghav-ys**
# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

### CODE REVIEW

**Comment by sobolevn** [comment]
@raghav-ys it works correctly.

```
----------- coverage: platform linux, python 3.7.1-final-0 -----------
Name                                               Stmts   Miss Branch BrPart  Cover   Missing
----------------------------------------------------------------------------------------------
wemake_python_styleguide/visitors/ast/modules.py      62      0     32      1    99%   88->exit
----------------------------------------------------------------------------------------------
TOTAL                                               4578      0   2052      1    99%
```

It indicates that `wemake_python_styleguide/visitors/ast/modules.py` is not covered (which is true).

**Comment by raghav-ys** [comment]
> Awesome! Can you please update tests as well?
> 
> See the original issue description, it contains useful details.

Sure, will work on it.

**Comment by sobolevn** [comment]
Oh, and please add a changelog entry.

**Comment by raghav-ys** [comment]
Sorry, closing this pull request, had to create a new pull request.

**Pull request closed without merging**
