### PR TITLE
Fix broken link for "Usage" section

### LINKED ISSUE #538: The "Usage" section was not found.
# Bug report

## What's wrong

Currently, in the [docs](https://wemake-python-styleguide.readthedocs.io/en/latest/) in the next phrase "See “Usage” section in the docs for examples and integrations." the ["Usage link"](https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage.html) is broken

## How is that should be
It should show the "usage" section instead, and not 404 :)

### flake8 information

Contents of `flake8 --bug-report`:

### pip information

Contents of `pip freeze`:

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
# I have made things!

## Checklist

- [ ] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [X] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #538

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Fix issue https://github.com/wemake-services/wemake-python-styleguide/issues/538, @sobolevn

**Comment by sobolevn** [comment]
Awesome! What about https://github.com/wemake-services/wemake-python-styleguide/issues/538#issuecomment-479615374 ?

**Comment by DmytroLitvinov** [comment]
Done ;)

**Comment by sobolevn** [comment]
Thanks again 🎉

**Pull request merged**
