### PR TITLE
Allow dot and comma to be overused string literals

### LINKED ISSUE #2209: Add exception to WPS226 to allow commas and dots
# Rule request

I suggest adding comma `,` and dot `.` to the list of allowed exceptions for WPS226

## Thesis

Forcing defining a constant for dot and comma strings worsen the code readability without need.

## Reasoning

It is a [classical](https://realpython.com/python-string-split-concatenate-join/#going-from-a-list-to-a-string-in-python-with-join) pattern to build a sentence with the code like:
```
strings = ['a', 'b', 'c']
','.join(strings)
```
It feels unnatural to define a constant (e.g. DOT, COMMA) for such obvious case.

Besides that the check WPS226 looks good. I don't like disabling it or increasing the number of string occurrences.
This extends the idea in https://github.com/wemake-services/wemake-python-styleguide/issues/1534

### PR DESCRIPTION
**Pull request by 0anton**
# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [x] I have created at least one test case for the changes I have made
- [x] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #2209 

**Remarks:**
- Added quotes to the reported overused string literal. I had bad time looking for the unescaped dot `.` in logs. Now the log will write it like `'.'`
- Replaced wording _string constrant overuse_ with _string literal overuse_. See for example [here](https://bic-berkeley.github.io/psych-214-fall-2016/string_literals.html#:~:text=A%20string%20literal%20is%20where,a%20string%20in%20a%20program.&text=The%20variable%20a%20is%20a,single%20or%20double%20quote%20delimiters.) for wording usage.
- Fixed wording in the unit test to better describe what it does.

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thanks a lot!

**Comment by 0anton** [comment]
Thanks for approving, @sobolevn ! I see that the [test](https://github.com/wemake-services/wemake-python-styleguide/pull/2210/checks?check_run_id=3806985797) is breaking. This is possibly related to the change in the format of the error message, I introduces. Do I have to look at it?

**Comment by sobolevn** [comment]
Yes, seems related. Can you please fix it?

**Comment by 0anton** [comment]
I fixed failing tests with this https://github.com/wemake-services/wemake-python-styleguide/pull/2210/commits/41d090c1ccfbb2f36013586a190ae013c84157f2. Could you @sobolevn please let the pipeline run again?

**Comment by 0anton** [comment]
Ah, my fault, I check that only `test_overused_string.py` is successful, not the complete test suit. I'll think of how to improve it and come back.

**Comment by sobolevn** [comment]
Thank you!

**Comment by 0anton** [comment]
Thank you for fixing tests and bringing this contribution for acceptance!

**Pull request merged**
