### PR TITLE
 Early return should not take return None form when it is not required

### PR DESCRIPTION
**Pull request by cdhiraj40**
# I have made things!

Closes https://github.com/wemake-services/wemake-python-styleguide/issues/2151

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [x] I have created at least one test case for the changes I have made
- [x] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

### CODE REVIEW

**Comment by cdhiraj40** [comment]
@sobolevn  I will do the documentation and other changes in sometime.

**Comment by cdhiraj40** [comment]
hey @sobolevn can you check?

**Comment by sobolevn** [comment]
You can start by fixing problems our CI finds: 
> wemake_python_styleguide/visitors/ast/keywords.py:131: error: Name "compat" is not defined

https://github.com/wemake-services/wemake-python-styleguide/pull/2171/checks?check_run_id=3492722559#step:7:8

**Comment by cdhiraj40** [comment]
@sobolevn it's not showing any errors now or do you have to approve?

**Comment by cdhiraj40** [comment]
@sobolevn hey I'm unable to understand these errors

**Comment by cdhiraj40** [comment]
@sobolevn sir can you help?

**Comment by sobolevn** [comment]
Done! I hope that my code will help you to understand what was wrong. What I did:
1. I have removed new violation, because we totally can reuse an existing one
2. I have fixed the check logic to suit our needs
3. I have added the same check for `yield`
4. I have fixed some tests, due to their new logic

That's it! The whole piece of work will be still sttributed to you. 

Thanks a lot for your help!
Do you have any questions?

**Comment by cdhiraj40** [comment]
> 4\. ave fixed some tests, due to their

Hey, I understood what was wrong, thanks for your help. I will happy to use this understanding in later use. Again thanks!

**Comment by sobolevn** [comment]
@cdhiraj40 feel free to pick any other issue! 👍

**Pull request merged**
