### PR TITLE
Drops `nitpick` support

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by sparrowt** [comment]
I eventually realised that this PR is the cause of the following error:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style.toml
```
which happens if you have configured a version of wemake-python-styleguide prior to 1.0.0 e.g. as documented here:
https://wemake-python-styleguide.readthedocs.io/en/0.19.2/pages/usage/integrations/nitpick.html
```
[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style.toml"
```
because https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style.toml no longer exists as of this PR.

An alternative is to either change to:
```
[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/0.19.2/styles/nitpick-style.toml"
```
or better still download it and bake it into your repo.

**Comment by sobolevn** [comment]
Yes, using tags is the recommended way.

**Comment by andreoliwa** [comment]
Hi @sobolevn! 👋🏻 
I just noticed you removed Nitpick from your style guide. 😢 😅 

Any special reason to drop it?
Anything I could improve in the tool?

I'd appreciate any feedback.

**Comment by andreoliwa** [comment]
> @andreoliwa the tool is awesome, but I just switched my workflow :)
> Since we now don't have any `flake8` plugins by design, it does not fit anymore :(

Thanks for the feedback, @sobolevn, and for the collaboration. 🙏🏻 
Nitpick received many stars through your free WPS advertisement. 🙂

We'll see each other around... cheers! 🎸🚀

**Pull request merged**
