### PR TITLE
Compare with ruff in README.md

### PR DESCRIPTION
**Pull request by blablatdinov**
# I have made things!

Include in compares table [ruff](https://github.com/astral-sh/ruff)

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

Ref:  #2976

🙏 Please, if you or your company is finding wemake-python-styleguide valuable, help us sustain the project by sponsoring it transparently on https://opencollective.com/wemake-python-styleguide. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

### CODE REVIEW

**Comment by blablatdinov** [comment]
@sobolevn take a look please

**Review by sobolevn — COMMENTED** [review]
I think that `ruff` also finds bugs :)

**Comment by blablatdinov** [comment]
> I think that ruff also finds bugs :)

Yes, you're right, put a check mark

**Review by sobolevn — APPROVED** [review]
Thanks!

**Pull request merged**
